// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAoqug-kyXj_vBX5Mu278OcoVnKKwO80t4',
    appId: '1:898331065553:android:d8d3497dde432577ee19f0',
    messagingSenderId: '898331065553',
    projectId: 'siba-5347f',
    storageBucket: 'siba-5347f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA2URaAVE2eNwQ7ll02wT8A33n84JcX2q8',
    appId: '1:898331065553:ios:76dfb67c16c607e3ee19f0',
    messagingSenderId: '898331065553',
    projectId: 'siba-5347f',
    storageBucket: 'siba-5347f.appspot.com',
    androidClientId: '898331065553-59agsiestriosikgnvf1vubvh734qdvf.apps.googleusercontent.com',
    iosClientId: '898331065553-t13e3vfoc248865fu49foc9mbjrailkm.apps.googleusercontent.com',
    iosBundleId: 'com.example.sibaWeather',
  );

}